server:
  port: 8083
  servlet:
    session:
      cookie:
        http-only: true
spring:
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
  application:
    name: app
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: #spring.profiles.active#
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    generate-ddl: true
    properties:
      "[hibernate.jdbc.time_zone]": UTC
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      enabled: true
  task:
    execution:
      thread-name-prefix: app-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: app-scheduling-
      pool:
        size: 2

app:
  cache:
    ehcache:
      time-to-live-seconds: 3600
      max-entries: 1000
  security:
    authentication:
      jwt:
      # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: glxxC0Yc0Pqp2qq+NAhVKEgC/mUwIi0xptBJyZxXE290YmtGY4LRj0Qdr5tcpfa1t6hbVpYf9AoB+h0NU22KhA==
        secret: wCyYpboXnOq94s6m1BkCD0D323MTXlUXj8kTbA15
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  cors:
    allowed-origins: '*'
#    allowed-methods: 'GET, PUT, POST, DELETE, OPTIONS'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800
  swagger:
    title: API
    description: API documentation
    version: version 1.0
    termsOfServiceUrl: http://springfox.io
    contact:
      name: app
      url: null
      email: app@qq.com
    license: Apache License Version 2.0
    licenseUrl: https://github.com/springfox/springfox/blob/master/LICENSE