camunda.bpm.metrics:
  enabled: false
  db-reporter-activate: false
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          ['configprops', 'env', 'health', 'info', 'jhimetrics', 'logfile', 'loggers', 'prometheus', 'threaddump', 'caches', 'liquibase']
  endpoint:
    health:
      show-details: when-authorized
      roles: 'ROLE_ADMIN'
      probes:
        enabled: true

spring:
  main:
    banner-mode: 'off'
    allow-bean-definition-overriding: true
  application:
    name: app
  profiles:
    # The commented value for `active` can be replaced with valid Spring profiles to load.
    # Otherwise, it will be filled in by maven when building the JAR file
    # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
    active: #spring.profiles.active#
    group:
      dev:
        - dev
        - api-docs
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    generate-ddl: true
    properties:
      "[hibernate.jdbc.time_zone]": UTC
      "[hibernate.id.new_generator_mappings]": true
      "[hibernate.connection.provider_disables_autocommit]": true
#      "[hibernate.cache.use_second_level_cache]": true
#      "[hibernate.cache.use_query_cache]": false
      "[hibernate.generate_statistics]": false
      # modify batch size as necessary
      "[hibernate.jdbc.batch_size]": 25
      "[hibernate.order_inserts]": true
      "[hibernate.order_updates]": true
      "[hibernate.query.fail_on_pagination_over_collection_fetch]": true
      "[hibernate.query.in_clause_parameter_padding]": true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  messages:
    basename: i18n/messages
  servlet:
    multipart:
      enabled: true
  task:
    execution:
      thread-name-prefix: app-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: app-scheduling-
      pool:
        size: 2

server:
  servlet:
    session:
      cookie:
        http-only: true

app:
  clientApp:
    name: 'app'
  security:
    authentication:
      jwt:
      # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: glxxC0Yc0Pqp2qq+NAhVKEgC/mUwIi0xptBJyZxXE290YmtGY4LRj0Qdr5tcpfa1t6hbVpYf9AoB+h0NU22KhA==
        secret: wCyYpboXnOq94s6m1BkCD0D323MTXlUXj8kTbA15
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
    content-security-policy: "default-src 'self'; frame-src 'self' data:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://storage.googleapis.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:"
  api-docs:
    default-include-pattern: ${server.servlet.context-path:}/api/.*
    management-include-pattern: ${server.servlet.context-path:}/management/.*
    title: API
    description: API documentation
    version: 0.0.1
    terms-of-service-url:
    contact-name:
    contact-url:
    contact-email:
    license: unlicensed
    license-url: